import { makeStyles } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
	[theme.breakpoints.down('sm')]: {
		contactWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			flexDirection: 'column',
			height: '100vh',
		},
		heading: {
			fontFamily: 'lobster',
			width: '100%',
			textAlign: 'center',
			fontSize: '15vw',
		},
		background: {
			background: theme.palette.primary.main,
			boxShadow: 'inset 0 0 3vw black',
			border: '1vw double white',
			borderRadius: '1.5vw',
			height: '50%',
		},
		infoWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'space-around',
			flexDirection: 'row',
		},
		infoSubHeading: {
			width: '20%',
			fontFamily: 'lobster',
		},
		infoSubDesc: {
			'width': '60%',
			'background': theme.palette.background.paper,
			'color': theme.palette.text.secondary,
			'padding': '2vw',
			'justifyContent': 'center',
			'& a': {
				textDecoration: 'none',
				color: theme.palette.text.secondary,
			},
			'borderRadius': '1vw',
		},
		subHeading: {
			fontSize: '7vw',
			borderBottom: `1vw solid ${theme.palette.background.paper}`,
			display: 'inline-block',
		},
		subDesc: {
			fontSize: '6vw',
			textAlign: 'center',
			margin: '0 auto',
			fontWeight: '400',
			fontStyle: 'italic',
		},
	},
	[theme.breakpoints.between('sm', 'md')]: {
		contactWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			flexDirection: 'column',
			height: '100vh',
		},
		heading: {
			fontFamily: 'lobster',
			width: '100%',
			textAlign: 'center',
			fontSize: '15vw',
		},
		background: {
			background: theme.palette.primary.main,
			boxShadow: 'inset 0 0 3vw black',
			border: '1vw double white',
			borderRadius: '1.5vw',
			height: '50%',
			width: '80%',
		},
		infoWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'space-around',
			flexDirection: 'row',
		},
		infoSubHeading: {
			width: '20%',
			fontFamily: 'lobster',
		},
		infoSubDesc: {
			'width': '60%',
			'background': theme.palette.background.paper,
			'color': theme.palette.text.secondary,
			'padding': '2vw',
			'justifyContent': 'center',
			'& a': {
				textDecoration: 'none',
				color: theme.palette.text.secondary,
			},
			'borderRadius': '1vw',
		},
		subHeading: {
			fontSize: '6vw',
			borderBottom: `1vw solid ${theme.palette.background.paper}`,
			display: 'inline-block',
		},
		subDesc: {
			fontSize: '4vw',
			textAlign: 'center',
			margin: '0 auto',
			fontWeight: '400',
			fontStyle: 'italic',
		},
	},
	[theme.breakpoints.between('md', 'lg')]: {
		contactWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			flexDirection: 'column',
			height: '100vh',
		},
		heading: {
			fontFamily: 'lobster',
			width: '100%',
			textAlign: 'center',
			fontSize: '6vw',
		},
		background: {
			background: theme.palette.primary.main,
			boxShadow: 'inset 0 0 3vw black',
			border: '1vw double white',
			borderRadius: '1.5vw',
			height: '50%',
			width: '80%',
		},
		infoWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			flexDirection: 'row',
		},
		infoSubHeading: {
			width: '10%',
			fontFamily: 'lobster',
			marginRight: '3.3vw',
		},
		infoSubDesc: {
			'width': '40%',
			'background': theme.palette.background.paper,
			'color': theme.palette.text.secondary,
			'padding': '2vw',
			'justifyContent': 'center',
			'& a': {
				textDecoration: 'none',
				color: theme.palette.text.secondary,
			},
			'borderRadius': '1vw',
		},
		subHeading: {
			fontSize: '3vw',
			borderBottom: `1vw solid ${theme.palette.background.paper}`,
			display: 'inline-block',
		},
		subDesc: {
			fontSize: '1.5vw',
			textAlign: 'center',
			margin: '0 auto',
			fontWeight: '400',
			fontStyle: 'italic',
		},
	},
	[theme.breakpoints.up('xl')]: {
		contactWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			flexDirection: 'column',
			height: '100vh',
		},
		heading: {
			fontFamily: 'lobster',
			width: '100%',
			textAlign: 'center',
			fontSize: '6vw',
		},
		background: {
			background: theme.palette.primary.main,
			boxShadow: 'inset 0 0 3vw black',
			border: '1vw double white',
			borderRadius: '1.5vw',
			height: '50%',
			width: '80%',
		},
		infoWrapper: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			flexDirection: 'row',
		},
		infoSubHeading: {
			width: '10%',
			fontFamily: 'lobster',
			marginRight: '3.3vw',
		},
		infoSubDesc: {
			'width': '40%',
			'background': theme.palette.background.paper,
			'color': theme.palette.text.secondary,
			'padding': '2vw',
			'justifyContent': 'center',
			'& a': {
				textDecoration: 'none',
				color: theme.palette.text.secondary,
			},
			'borderRadius': '1vw',
		},
		subHeading: {
			fontSize: '3vw',
			borderBottom: `1vw solid ${theme.palette.background.paper}`,
			display: 'inline-block',
		},
		subDesc: {
			fontSize: '1.5vw',
			textAlign: 'center',
			margin: '0 auto',
			fontWeight: '400',
			fontStyle: 'italic',
		},
	},
}))
